services:
  casa:
    image: dockurr/casa
    container_name: casa
    ports:
      - 9090:8080
    volumes:
      - ./casa:/DATA
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    stop_grace_period: 1m
